version: '3.8'

services:
  ctrl:
    container_name: "mg-nicoSV"
    build: ./Dockerfiles
    tty: true
    volumes:
      - ./app:/app
      - ./env:/app/env
    ports:
      - "6010:5001"
    env_file: .env
#   environment:
#     VIRTUAL_HOST: sample.com
#     LETSENCRYPT_HOST: sample.com
#     LETSENCRYPT_EMAIL: youremail@test.local
    # depends_on:
    #   - mongo # for connection of mongoDB
    restart: always

  # mariadbSet:
  #   image: mariadb:latest
  #   container_name: "lsl-mariadb"
  #   volumes:
  #     - ./mariadb:/var/lib/mysql
  #     - ./initdb.d:/docker-entrypoint-initdb.d
  #   ports:
  #     - "3326:3306"
  #   env_file: ./env/.mariaEnv
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=xxyyzz

  # api:
  #   container_name: "lsl-api"
  #   build: ./node
  #   restart: unless-stopped
  #   volumes:
  #     - ./app/node:/app/node
  #   working_dir: /app/node
  #   ports:
  #     - "3021:3000"
  #   command: sh -c "npm install -g pm2 && npm install && pm2-runtime app.js --watch"

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: "lsl-mariadb-admin"
  #   env_file: ./env/.phpmyadEnv
  #   links:
  #     - mariadbSet
  #   ports:
  #     - 8089:80
#   depends_on:
#     - mariadb
    # volumes:
    #   - ./phpmyadmin/sessions:/sessions
    #   - ./phpmyadmin/var_www_html:/var/www/html

  # mongo:
    # image: 'mongo:4.2.3-bionic'
    # container_name: "lsl-mongoDB"
    # env_file: ./env/.mongoEnv
#    environment:
#       MONGO_INITDB_ROOT_USERNAME: ${ENV_MONGO_INITDB_ROOT_USERNAME}
#       MONGO_INITDB_ROOT_PASSWORD: ${ENV_MONGO_INITDB_ROOT_PASSWORD}
#       MONGO_INITDB_DATABASE: ${ENV_MONGO_INITDBNAME}
    # ports:
    #   - 27017:27017
    # volumes:
    #   - ./mongodb-data:/data/db
    #   - ./mongo/initdb.d/:/docker-entrypoint-initdb.d
#    command: mongod --port 27017

  # mongo-express:
  #   image: mongo-express
  #   container_name: lsl-mongo-express
  #   depends_on:
  #     - mongo
  #   ports:
  #     - '8181:8081'
  #   env_file: ./env/.mongoExpEnv
#    environment:
#      ME_CONFIG_MONGODB_ENABLE_ADMIN: false
#     - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
#     - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
#    command: env

    #networks:
    #  default:
    #    external:
    #      name: common_link

# volumes:
#   mongodb-data: {}

